### PR TITLE
add functions to compute Julian day from year of simulation start

### PR DESCRIPTION
**Pull request by timflutre**
# Add functions to compute Julian day from year of simulation start

## Description

I added 3 functions, only one being exported: `julian_date_for_stics`. It takes two inputs, `date` (the date to convert in Julian day) and `start_date` (the reference point, typically the start of a simulation), and returns the Julian day corresponding to `date`. It handles leap years.

I added tests, too.

Several people asked for such a function during the training session.

There is no dependency.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

I built the package and ran `R MD check`: it returned "ok".

**Test Configuration**:
* R version: 4.2.2
* OS: GNU/Linux (Debian)

### CODE REVIEW

**Comment by plecharpent** [comment]
Hi @timflutre,

First, thank you for your proposition of a usefull function.

We would like to precise some things for better understanding of the function goal.

Is the idea to calculate the day number from the first year of simulation from a date in the first or the second year in order 
to set days number of crop management operations (i.e. water supply, tillage and so on) ?

But we do no understand, why for one year the result is the day number from the first date, but not from the first day of the current year (i.e. day of year).

Is there a reason for that ?

After clarification, would you like to make changes or we do it ourselves ?

Thank you for your reply.
All the best.

**Comment by timflutre** [comment]
From what I understand, STICS has its own way to specify dates for crop management operations. Instead of using the calendar date, one has to use an integer from a reference date. Whether this reference date is the fist day of the year or the first day of the simulation, my function `julian_date_for_stics` can be used.

But you wrote "why for one year the result is the day number from the first date, but not from the first day of the current year (i.e. day of year)".

Well, I asked you the same question with the following example:
```
simul_start_date <- as.Date("2014-08-01")
operation_date <- as.Date("2015-02-10")
```

And you answered `expected <- 406`, so that's what I implemented.

What is wrong? What should be the answer? If this is the wrong answer, then it seems clear to me that I did not understand how STICS requires its date to be specified.

**Comment by sbuis** [comment]
Hi Thimothée,

Yes in the case you mentioned, the expected answer is 406 and your code provide this expected result.

Let's now consider the case  

```
simul_start_date <- as.Date("2014-08-01")
operation_date <- as.Date("2014-08-10")
```
The expected result is 222, while from what I understood, your code will give 10, i.e. the behavior of your function is different depending on whether the date to calculate is the same year as start date or not.

Does this help?

all the best,
Samuel

**Comment by timflutre** [comment]
Ok, now I think I understand what you are expecting. And from the questions people asked during the training session, I think I am not the only one ;)
I will change the unit tests and the implementation.

**Comment by plecharpent** [comment]
Hi Timothee,
Just a little comment about the function name.
We discussed about it and we propose to rename `get_julian_days` with `day_from_date` if you agree with that.

Another remark, also for the team, would it be useful to add a function doing the reverse job `date_from_day`.

Thanks again for your contribution.
Patrice

**Comment by timflutre** [comment]
I changed the first unit test as well as the implementation in the case where `date` and`start_date` are from the same year. Is it ok for you?

Typically, as a user, I would need this function when preparing `param_df` before using `gen_tec_xml()`.

**Comment by timflutre** [comment]
@plecharpent I would suggest keeping `julian` in the name, that is `julian_day_from_date`, is it ok for you? if yes, I can change the name.

**Comment by sbuis** [comment]
Hi,

I think we proposed 'compute_day_from_date' (not 'day_from_date' ;-) ), to be homogeneous with the coding style we use (use a verb as prefix for each function).

Samuel

**Comment by sbuis** [comment]
We prefer day than julian_day since what we compute is actually not a julian day but a day number (julian days are supposed to be computed from 01/01/-4712, see https://fr.wikipedia.org/wiki/Jour_julien).

**Comment by plecharpent** [comment]
Yes Samuel you are right for the function name, I forgot that.

**Comment by timflutre** [comment]
Ok I agree. I will rename `get_julian_day` into `compute_day_from_date`.

I will also rename `isLeapYear` into `is_leap_year`.

And what about `julian_dates_for_stics` (the only exported function): how would you like it to be renamed?

**Comment by sbuis** [comment]
Actually it is the exported function that we would like to rename 'compute_day_from_date' :-).

**Comment by plecharpent** [comment]
Yes, another confusion from my side.

The `get_julian_days` may be renamed to `day_of_year``or something like that

And the file R file may be renamed without julian in it.

**Comment by timflutre** [comment]
I pushed a new commit after changing the function names. There is one test failing but I don't know why. Is it because I did not merge the latest commits of the `main` base branch?

**Comment by plecharpent** [comment]
No, I dont think so, I did the merge but this action is still failing.

I saw that the failing test does not start because of an authentication issue. It is triggered after all the others succeed.
I have to check how to configure that when the pull request is coming from a forked repo.

**Comment by timflutre** [comment]
Ok, let me know if you need anything from me.

**Comment by timflutre** [comment]
Would it be possible to merge this pull request? The failing test does not seem to be important. Moreover, I have an intern coming soon. She will need theses functions, and it would be easier if she could directly download SticsRFiles rather than my fork.

**Pull request merged**
